### ISSUE TITLE
OctoPrint-OctoPod not installing

### ISSUE THREAD

**Issue by DarrenSchwartz** [gdombiak/OctoPod#682]
I'm not able to install the OctoPrint-OctoPod plugin on Octoprint 1.9.3 running on an Orange Pi PC with dietpi (Armbian 6.1.63-current-sunxi). Had no problem installing a different plugin. The last few lines of the plugin log below seem interesting (some talk of successfully uninstalling). I have no idea how to interpret this though. Any help appreciated.

```
Installing plugin "OctoPrint-OctoPod" from https://github.com/gdombiak/OctoPrint-OctoPod/archive/master.zip...
/usr/bin/python3 -m pip --disable-pip-version-check install file:///tmp/tmplflhclbm/OctoPrint-OctoPod-master.zip --no-cache-dir --user
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple/
Processing /tmp/tmplflhclbm/OctoPrint-OctoPod-master.zip
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: OctoPrint in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint-OctoPod==0.3.16) (1.9.3)
Requirement already satisfied: pillow in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint-OctoPod==0.3.16) (10.1.0)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2021.2.23)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.10.11 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2021.10.11)
Requirement already satisfied: OctoPrint-PiSupport>=2023.5.24 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2023.7.31)
Requirement already satisfied: argon2-cffi<22,>=21.3.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (21.3.0)
Requirement already satisfied: Babel<2.13,>=2.12.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.12.1)
Requirement already satisfied: cachelib<0.11,>=0.10.2 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.10.2)
Requirement already satisfied: Click<9,>=8.1.3 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (8.1.7)
Requirement already satisfied: colorlog<7,>=6.7.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (6.7.0)
Requirement already satisfied: emoji<3,>=2.2.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.8.0)
Requirement already satisfied: feedparser<7,>=6.0.10 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (6.0.10)
Requirement already satisfied: filetype<2,>=1.2.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.2.0)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.0)
Requirement already satisfied: Flask-Babel<4,>=3.1.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (3.1.0)
Requirement already satisfied: Flask-Login<0.7,>=0.6.2 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.6.2)
Requirement already satisfied: Flask-Limiter<4,>=3.3.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (3.3.1)
Requirement already satisfied: flask<2.3,>=2.2.3 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.2.5)
Requirement already satisfied: frozendict<3,>=2.3.7 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.3.8)
Requirement already satisfied: future<1,>=0.18.3 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.18.3)
Requirement already satisfied: markdown<4,>=3.4.3 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (3.4.4)
Requirement already satisfied: netaddr<0.9,>=0.8 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.8.0)
Requirement already satisfied: netifaces<1,>=0.11 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.11.0)
Requirement already satisfied: passlib<2,>=1.7.4 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.7.4)
Requirement already satisfied: pathvalidate<3,>=2.5.2 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.5.2)
Requirement already satisfied: pkginfo<2,>=1.9.6 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.9.6)
Requirement already satisfied: psutil<6,>=5.9.4 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (5.9.5)
Requirement already satisfied: pydantic==1.10.12 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.10.12)
Requirement already satisfied: pylru<2,>=1.2.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.2.1)
Requirement already satisfied: pyserial<4,>=3.5 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (3.5)
Requirement already satisfied: PyYAML<7,>=6.0.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (6.0.1)
Requirement already satisfied: requests<3,>=2.28.2 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.31.0)
Requirement already satisfied: sarge==0.1.7.post1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.1.7.post1)
Requirement already satisfied: semantic-version<3,>=2.10.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.10.0)
Requirement already satisfied: sentry-sdk<2,>=1.19.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.29.2)
Requirement already satisfied: tornado<7,>=6.2 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (6.3.3)
Requirement already satisfied: watchdog<3,>=2.3.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.3.1)
Requirement already satisfied: websocket-client<2,>=1.5.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.6.1)
Requirement already satisfied: werkzeug<2.3,>=2.2.3 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2.2.3)
Requirement already satisfied: wrapt<1.16,>=1.15 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.15.0)
Requirement already satisfied: zeroconf==0.39.4 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.39.4)
Requirement already satisfied: zipstream-ng<2.0.0,>=1.5.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.6.0)
Requirement already satisfied: blinker<2,>=1.6.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.6.2)
Requirement already satisfied: class-doc<0.3,>=0.2.6 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.2.6)
Requirement already satisfied: regex in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (2023.8.8)
Requirement already satisfied: unidecode in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (1.3.6)
Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (from OctoPrint->OctoPrint-OctoPod==0.3.16) (0.41.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from pydantic==1.10.12->OctoPrint->OctoPrint-OctoPod==0.3.16) (4.7.1)
Requirement already satisfied: async-timeout>=4.0.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from zeroconf==0.39.4->OctoPrint->OctoPrint-OctoPod==0.3.16) (4.0.3)
Requirement already satisfied: ifaddr>=0.1.7 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from zeroconf==0.39.4->OctoPrint->OctoPrint-OctoPod==0.3.16) (0.2.0)
Requirement already satisfied: argon2-cffi-bindings in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from argon2-cffi<22,>=21.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (21.2.0)
Requirement already satisfied: more-itertools>=5.0.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from class-doc<0.3,>=0.2.6->OctoPrint->OctoPrint-OctoPod==0.3.16) (10.1.0)
Requirement already satisfied: sgmllib3k in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from feedparser<7,>=6.0.10->OctoPrint->OctoPrint-OctoPod==0.3.16) (1.0.0)
Requirement already satisfied: Jinja2>=3.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from flask<2.3,>=2.2.3->OctoPrint->OctoPrint-OctoPod==0.3.16) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from flask<2.3,>=2.2.3->OctoPrint->OctoPrint-OctoPod==0.3.16) (2.1.2)
Requirement already satisfied: webassets>=2.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (2.0)
Requirement already satisfied: pytz>=2022.7 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from Flask-Babel<4,>=3.1.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (2023.3)
Requirement already satisfied: limits>=2.8 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (3.5.0)
Requirement already satisfied: ordered-set<5,>4 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (4.1.0)
Requirement already satisfied: rich<14,>=12 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (13.5.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-OctoPod==0.3.16) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-OctoPod==0.3.16) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-OctoPod==0.3.16) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from requests<3,>=2.28.2->OctoPrint->OctoPrint-OctoPod==0.3.16) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from werkzeug<2.3,>=2.2.3->OctoPrint->OctoPrint-OctoPod==0.3.16) (2.1.3)
Requirement already satisfied: deprecated>=1.2 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (1.2.14)
Requirement already satisfied: importlib-resources>=1.3 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (6.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (68.1.2)
Requirement already satisfied: packaging<24,>=21 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from limits>=2.8->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (23.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from rich<14,>=12->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from rich<14,>=12->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (2.16.1)
Requirement already satisfied: cffi>=1.0.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from argon2-cffi-bindings->argon2-cffi<22,>=21.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (1.15.1)
Requirement already satisfied: pycparser in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi<22,>=21.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (2.21)
Requirement already satisfied: mdurl~=0.1 in /mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich<14,>=12->Flask-Limiter<4,>=3.3.0->OctoPrint->OctoPrint-OctoPod==0.3.16) (0.1.2)
Building wheels for collected packages: OctoPrint-OctoPod
Building wheel for OctoPrint-OctoPod (setup.py): started
Building wheel for OctoPrint-OctoPod (setup.py): finished with status 'done'
Created wheel for OctoPrint-OctoPod: filename=OctoPrint_OctoPod-0.3.16-py3-none-any.whl size=45749 sha256=5833b271121ffbc68b9e475d9ded8292d246e0189d796cf9dbf4a6e907bb4104
Stored in directory: /tmp/pip-ephem-wheel-cache-tjuxhhbz/wheels/f6/3e/e0/c392d9d86e0aacc5409516b689ab4017699ec8fef8157c23ce
Successfully built OctoPrint-OctoPod
Installing collected packages: OctoPrint-OctoPod
Attempting uninstall: OctoPrint-OctoPod
Found existing installation: OctoPrint-OctoPod 0.3.16
Uninstalling OctoPrint-OctoPod-0.3.16:
Successfully uninstalled OctoPrint-OctoPod-0.3.16
Successfully installed OctoPrint-OctoPod-0.3.16
Done!
```

And the relevant looking section of `octoprint.log`. Seems to be missing dependencies? If so, why are they not being installed?

```
2023-12-20 21:30:35,648 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2023-12-20 21:30:38,772 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2023-12-20 21:30:40,580 - octoprint.server.util.sockjs - INFO - User dietpi logged in on the socket from client 192.168.5.117
2023-12-20 21:30:42,906 - octoprint.plugins.tracking - INFO - Sent tracking event webui_load, payload: {'browser_name': 'Firefox', 'browser_version': '121.0', 'os_name': 'Windows', 'os_version': '10'}
2023-12-20 21:31:08,387 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/gdombiak/OctoPrint-OctoPod/archive/master.zip
2023-12-20 21:31:09,506 - octoprint.plugin.core - ERROR - Error loading plugin octopod
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/plugin/core.py", line 1294, in _import_plugin
    module = _load_module(module_name, spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/plugin/core.py", line 52, in _load_module
    return imp.load_module(name, f, filename, details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
           ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint_octopod/__init__.py", line 14, in <module>
    from .spool_manager import SpoolManagerNotifications
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint_octopod/spool_manager.py", line 1, in <module>
    from .base_notification import BaseNotification
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint_octopod/base_notification.py", line 4, in <module>
    from PIL import Image
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
2023-12-20 21:31:09,625 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2023.7.31) did not pass check, not loading.
2023-12-20 21:31:29,041 - octoprint.plugin.core - ERROR - Error loading plugin octopod
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/plugin/core.py", line 1294, in _import_plugin
    module = _load_module(module_name, spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/plugin/core.py", line 52, in _load_module
    return imp.load_module(name, f, filename, details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
           ^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint_octopod/__init__.py", line 14, in <module>
    from .spool_manager import SpoolManagerNotifications
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint_octopod/spool_manager.py", line 1, in <module>
    from .base_notification import BaseNotification
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/octoprint_octopod/base_notification.py", line 4, in <module>
    from PIL import Image
  File "/mnt/dietpi_userdata/octoprint/.local/lib/python3.11/site-packages/PIL/Image.py", line 82, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
2023-12-20 21:31:29,163 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2023.7.31) did not pass check, not loading.
2023-12-20 21:31:29,183 - octoprint.plugins.pluginmanager - WARNING - The plugin was installed successfully, but couldn't be found afterwards to initialize properly during runtime. Please restart OctoPrint.
```

**Comment by gdombiak** [comment]
Hi @DarrenSchwartz,

That's interesting. This seems to be an error in the PIL package that is not loading a dependency. Based on information on the internet a quick fix is to install libopenjp2-7 by running this from ssh/command line in your RPi.

> sudo apt install libopenjp2-7

I'm curious about your setup and why it's missing that dependency.

Thanks,
Gaston

**Comment by DarrenSchwartz** [comment]
Well thanks! That did the trick! If you care to investigate, here is my Octoprint system info dump. I skimmed them all and I'm not concerned about anything being sensitive. Well aware that some local IP addresses and printing details are in there - no big deal.

[octoprint-systeminfo-20231220214232.zip](https://github.com/gdombiak/OctoPod/files/13746759/octoprint-systeminfo-20231220214232.zip)
